import"./assets/styles-COSbD4d6.js";import{a as r}from"./assets/vendor-N5iQpiFS.js";const v="https://dummyjson.com",a={CATEGORIES:"/products/category-list",PRODUCTS:"/products",PRODUCTS_BY_CATEGORY:"/products/category/",PRODUCT_BY_ID:"/products/"},d=12;r.defaults.baseURL=v;async function T(){const{data:t}=await r.get(a.CATEGORIES);return t}async function m(t){const e=(t-1)*12,{data:o}=await r.get(`${a.PRODUCTS}?limit=${d}&skip=${e}`);return o}async function k(t,e){const o=(e-1)*12,{data:n}=await r.get(`${a.PRODUCTS_BY_CATEGORY}${t}?limit=${d}&skip=${o}`);return n}async function C(t){const{data:e}=await r.get(`${a.PRODUCT_BY_ID}${t}`);return e}const c={categorisEls:document.querySelector(".categories"),productsEls:document.querySelector(".products"),modalEl:document.querySelector(".modal"),modalInfo:document.querySelector(".modal-product")};function R(t){const e=t.map(o=>`<li class="categories__item">
   <button class="categories__btn" type="button">${o}</button>
 </li>`).join("");c.categorisEls.innerHTML=e}function _(t){const e=t.map(({id:o,thumbnail:n,title:s,brand:i,category:l,price:u})=>`
        <li class="products__item" data-id="${o}">
    <img class="products__image" src="${n}" alt="${s}"/>
    <p class="products__title">${s}</p>
    <p class="products__brand"><span class="products__brand--bold">Brand: ${i}</span></p>
    <p class="products__category">Category: ${l}</p>
    <p class="products__price">Price: ${u}</p>
 </li>`).join("");c.productsEls.insertAdjacentHTML("beforeend",e)}function f(){document.querySelector(".loader").classList.remove("is-hidden")}function g(){document.querySelector(".load-more-btn").classList.remove("is-hidden")}function y(){document.querySelector(".loader").classList.add("is-hidden")}function E(){document.querySelector(".load-more-btn").classList.add("is-hidden")}function L(){document.querySelector(".not-found").classList.add("not-found--visible")}function $(){document.querySelector(".not-found").classList.remove("not-found--visible")}function B(){c.productsEls.innerHTML=""}function O({title:t,thumbnail:e,tags:o,description:n,price:s,shippingInformation:i,returnPolicy:l}){const u=o.map(S=>`<li>${S}</li>`).join(""),w=`<img class="modal-product__img" src="${e}" alt="${t}" />
      <div class="modal-product__content">
        <p class="modal-product__title">${t}</p>
        <ul class="modal-product__tags">${u}</ul>
        <p class="modal-product__description">${n}</p>
        <p class="modal-product__shipping-information">Shipping: ${i}</p>
        <p class="modal-product__return-policy">Return Policy: ${l}</p>
        <p class="modal-product__price">Price: ${s}$</p>
        <button class="modal-product__buy-btn" type="button">Buy</button>
      </div>
  `;c.modalInfo.innerHTML=w}function q(){c.modalEl.classList.add("modal--is-open"),document.body.style.overflow="hidden",window.addEventListener("keydown",h),c.modalEl.addEventListener("click",P)}function b(){c.modalEl.classList.remove("modal--is-open"),document.body.style.overflow="",window.removeEventListener("keydown",h),c.modalEl.removeEventListener("click",P)}function h(t){t.code==="Escape"&&b()}function P(t){t.target===t.currentTarget&&b()}let p=1;async function I(){try{f(),E(),$();const t=await T();if(t.length>0){const s=["all",...t];R(s),document.querySelector(".categories__btn").classList.add("categories__btn--active")}const{products:e,skip:o,total:n}=await m(p);e.length>0?(_(e),n-o-d>0&&g()):L()}catch(t){console.error(t)}finally{y()}}async function D(t){if(t.target.nodeName!=="BUTTON")return;document.querySelectorAll(".categories__btn").forEach(o=>o.classList.remove("categories__btn--active")),t.target.classList.add("categories__btn--active");const e=t.target.textContent;try{B(),f(),E(),$();const{products:o,skip:n,total:s}=e==="all"?await m(p):await k(e,p);o.length>0?(_(o),s-n-d>0&&g()):L()}catch(o){console.error(o)}finally{y()}}async function A(t){if(t.target.parentElement.nodeName!=="LI")return;const e=t.target.parentElement.dataset.id;try{if(e){const o=await C(e);o&&(q(),O(o))}}catch(o){console.log(o)}}document.addEventListener("DOMContentLoaded",I);c.categorisEls.addEventListener("click",D);c.productsEls.addEventListener("click",A);
//# sourceMappingURL=index.js.map
